name: Deploy internal artifact

on:
  push:
    branches:
      - develop

jobs:
  deploy-internal:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Assemble output jar
        run: ./gradlew assemble

      - name: Upload output jar
        uses: actions/upload-artifact@v3
        with:
          name: cicdworkshop-output
          path: build/libs/
